"""Add image column to jobs table

Revision ID: 296bac00d456
Revises: f5d2a549b13b
Create Date: 2025-06-28 20:39:26.401666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296bac00d456'
down_revision = 'f5d2a549b13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
