"""Add job_type, image, salary_range, expires_date to Job model

Revision ID: b7f797426a13
Revises: fff2ff51c7d3
Create Date: 2025-06-27 09:58:57.041330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f797426a13'
down_revision = 'fff2ff51c7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('expires_date')

    # ### end Alembic commands ###
