"""Add job_type to Job

Revision ID: fff2ff51c7d3
Revises: ff49d989093f
Create Date: 2025-06-27 09:49:55.695202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff2ff51c7d3'
down_revision = 'ff49d989093f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('job_type')

    # ### end Alembic commands ###
